name = "polyu-calendar-subscription"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "polyu-calendar-subscription-v1"
database_id = "polyu-calendar-subscription" # Placeholder

[cors]
origins = ["*"]
methods = ["GET", "POST", "OPTIONS", "DELETE"]
